#cloud-config

coreos:
  units:
    - name: kubernetes-minion-params.service
      command: start
      content: |
        [Unit]
        Description=Fetch kubernetes-minion-params
        Requires=network-online.target
        After=network-online.target

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/curl --fail --silent --show-error \
        -H "X-Google-Metadata-Request: True" \
        -o /etc/kubernetes-minion-params \
        http://169.254.169.254/computeMetadata/v1/instance/attributes/kubernetes-minion-params

    - name: etcd.service
      mask: true

    - name: fleet.socket
      command: start
      content: |
        [Socket]
        ListenStream=/var/run/fleet.sock

    - name: fleet.service
      command: start
      content: |
        [Unit]
        Description=fleet daemon
        Wants=kubernetes-minion-params.service
        After=kubernetes-minion-params.service
        Wants=fleet.socket
        After=fleet.socket
        [Service]
        EnvironmentFile=/etc/kubernetes-minion-params
        Environment="FLEET_METADATA=role=node"
        ExecStart=/usr/bin/fleetd
        Restart=always
        RestartSec=10s

    - name: kubernetes-install-minion.service
      command: start
      content: |
        [Unit]
        Description=Install Kubernetes Server
        Requires=network-online.target
        After=network-online.target
        Requires=kubernetes-minion-params.service
        After=kubernetes-minion-params.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        EnvironmentFile=/etc/kubernetes-minion-params
        ExecStartPre=/usr/bin/mkdir -p /opt/kubernetes/pkg
        ExecStartPre=/usr/bin/curl --location --create-dirs --output /opt/kubernetes/pkg/kubernetes-server-linux-amd64.tar.gz ${SERVER_BINARY_TAR_URL}
        ExecStart=/usr/bin/tar xf /opt/kubernetes/pkg/kubernetes-server-linux-amd64.tar.gz -C /opt --overwrite

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubelet
        Requires=kubernetes-install-minion.service
        After=kubernetes-install-minion.service
        Requires=kubernetes-minion-params.service
        After=kubernetes-minion-params.service

        [Service]
        EnvironmentFile=/etc/kubernetes-minion-params
        ExecStart=/opt/kubernetes/server/bin/kubelet \
        --etcd_servers=http://${KUBE_MASTER_INTERNAL_IP}:4001 \
        --api_servers=http://${KUBE_MASTER_INTERNAL_IP}:8080 \
        --address=0.0.0.0 \
        --config=/etc/kubernetes/manifests \
        --allow_privileged=false \
        --logtostderr=true

    - name: kube-proxy.service
      command: start
      content: |
        [Unit]
        Description=Kubelet
        Requires=kubernetes-install-minion.service
        After=kubernetes-install-minion.service
        Requires=kubernetes-minion-params.service
        After=kubernetes-minion-params.service

        [Service]
        EnvironmentFile=/etc/kubernetes-minion-params
        ExecStart=/opt/kubernetes/server/bin/kube-proxy \
        --etcd_servers=http://${KUBE_MASTER_INTERNAL_IP}:4001 \
        --master=http://${KUBE_MASTER_INTERNAL_IP}:8080 \
        --logtostderr=true

    - name: container-bridge.service
      command: start
      content: |
        [Unit]
        Description=Fetches and runs container_bridge.sh script
        Requires=network-online.target
        After=network-online.target

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        EnvironmentFile=/etc/kubernetes-minion-params
        ExecStartPre=/usr/bin/mkdir -p /opt/kubernetes
        ExecStartPre=/bin/curl --fail --silent --show-error \
        -H "X-Google-Metadata-Request: True" \
        -o /opt/kubernetes/container_bridge.sh \
        http://169.254.169.254/computeMetadata/v1/instance/attributes/container-bridge-sh
        ExecStartPre=/usr/bin/chmod 0755 /opt/kubernetes/container_bridge.sh
        ExecStart=/opt/kubernetes/container_bridge.sh

    - name: docker.service
      command: start
      content: |
        [Unit]
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.com
        After=docker.socket network-online.target
        Requires=docker.socket network-online.target

        [Service]
        LimitNOFILE=1048576
        LimitNPROC=1048576
        Environment=TMPDIR=/var/tmp
        Environment=DOCKER_OPTS='--bridge="cbr0" --iptables=false --ip-masq=false -r=false'
        EnvironmentFile=/etc/kubernetes-minion-params
        ExecStart=/usr/bin/docker -d --host=fd:// $DOCKER_OPTS $EXTRA_DOCKER_OPTS
        Restart=always
        RestartSec=10
